version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: chattrix_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: chattrix
      POSTGRES_USER: chattrix_user
      POSTGRES_PASSWORD: chattrix_password
    volumes:
      - ./data/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: chattrix_redis
    restart: unless-stopped


  backend:
    build: ./django
    container_name: chattrix_backend
    restart: unless-stopped
    volumes:
      - ./data/staticfiles:/app/staticfiles
      - ./data/media:/app/media
    depends_on:
      - redis
      - postgres
    environment:
      POSTGRES_DB: chattrix
      POSTGRES_USER: chattrix_user
      POSTGRES_PASSWORD: chattrix_password

  frontend:
    build: ./vue
    container_name: chattrix_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./data/staticfiles:/app/staticfiles:ro
      - ./data/media:/app/media:ro
    depends_on:
      - backend

