version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: chattrix_redis
    restart: unless-stopped

  backend:
    build: ./django
    container_name: chattrix_backend
    restart: unless-stopped
    volumes:
      - ./data/staticfiles:/app/staticfiles
      - ./data/media:/app/media
      - ./data/data/:/app/data
    depends_on:
      - redis
    ports:
      - "8000:8000"
