version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: chattrix_redis
    restart: unless-stopped


  backend:
    build: ./django
    container_name: chattrix_backend
    restart: unless-stopped
    volumes:
      - ./data/staticfiles:/app/staticfiles
      - ./data/media:/app/media
      - ./data/data/:/app/data
    depends_on:
      - redis

  frontend:
    build: ./vue
    container_name: chattrix_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./data/staticfiles:/app/staticfiles:ro
      - ./data/media:/app/media:ro
    depends_on:
      - backend

